"""Seed the catalog_items table. Safe to run multiple times (skips if already seeded)."""
import asyncio
import aiosqlite
from database import DB_PATH, init_db

CATALOG = [
    # ── Foreplay ─────────────────────────────────────────────────────────
    ("Slow Massage", "foreplay", "Full body, no rush. Let the tension build on its own.", "🫶", "standard"),
    ("Ice & Warmth", "foreplay", "Alternate between ice cubes and warm breath. Trace slow lines.", "🧊", "quick"),
    ("Blindfolded Touch", "foreplay", "One of you can't see. Every sensation becomes a surprise.", "🙈", "standard"),
    ("Strip Tease", "foreplay", "Low lights, good music. Make a show of it.", "🎵", "standard"),
    ("Giving Only", "foreplay", "One person receives, no reciprocation expected. Just giving.", "💋", "standard"),
    ("Talk It Out", "foreplay", "Say what you want before you do it. Be bold.", "🗣️", "quick"),
    ("Body Worship", "foreplay", "Kiss every inch. Tell them what you love about each part.", "✨", "standard"),
    ("Mirror Play", "foreplay", "Watch each other. Show them exactly what you like.", "👀", "standard"),
    ("Neck & Ears", "foreplay", "Just focus there. Breathing, kissing, whispering. Nothing else.", "🌬️", "quick"),
    ("Teasing Only", "foreplay", "Get close but don't finish. See how long you can both last.", "😈", "standard"),
    ("Shower Together", "foreplay", "Soap each other up slowly. Let the hot water do its thing.", "🚿", "quick"),
    ("Feather Touch", "foreplay", "Barely-there fingertips across skin. Goosebumps guaranteed.", "🪶", "quick"),
    ("Scalp Massage", "foreplay", "Slow, firm fingers through the hair. Melts tension immediately.", "🤲", "quick"),
    ("Kissing Only", "foreplay", "Nothing else. Just mouths, for as long as you can stand it.", "😘", "quick"),
    ("Gentle Biting", "foreplay", "Necks, shoulders, collarbones. Leave something to remember.", "🐺", "standard"),
    ("Inner Thigh Focus", "foreplay", "Get close but stay there. Tease until they can't take it.", "🌡️", "standard"),
    ("Slow Hands", "foreplay", "Deliberate and focused. Pay attention to every reaction.", "🤍", "standard"),
    ("Breathwork Together", "foreplay", "Sync your breathing. Press foreheads together. No rushing.", "🌬️", "quick"),
    ("Warm-Up Spanking", "foreplay", "Start soft, build gradually. Read their reaction and adjust.", "🖐️", "standard"),
    ("Hair Pulling", "foreplay", "Grip at the root. Slow and deliberate. Watch their expression.", "✊", "quick"),
    ("Playful Commands", "foreplay", "Tell them exactly what to do. See if they listen.", "🔥", "standard"),
    ("Take the Lead", "foreplay", "Full control of the pace. They follow your rhythm.", "😮", "standard"),
    ("Hands Pinned", "foreplay", "Hold their wrists above their head. Don't let them move.", "📌", "standard"),
    ("Sensitive Spots", "foreplay", "Spend real time on the places that make them gasp.", "🌸", "quick"),
    ("Worship from Below", "foreplay", "On your knees. Complete devotion from the ground up.", "👢", "standard"),
    ("Over the Knee", "foreplay", "Classic position. Slow build, check in, enjoy the warmth.", "🖐️", "standard"),
    ("Rope Teasing", "foreplay", "Drag soft rope across skin without tying. The texture alone is enough.", "🎗️", "quick"),
    ("Going Down", "foreplay", "Take your time. No rush to go anywhere else.", "👅", "standard"),
    ("Food Play", "foreplay", "Whipped cream, honey, chocolate — taste it off each other.", "🍓", "standard"),
    ("Chest Focus", "foreplay", "Between, around, across. Make it the main event for a while.", "🌸", "quick"),

    # ── Positions ────────────────────────────────────────────────────────
    ("Spooning", "positions", "Intimate, close, lazy. Perfect for slow mornings.", "🥄", "quick"),
    ("On Top (Them)", "positions", "Let them take control of the pace and depth.", "👆", "standard"),
    ("On Top (You)", "positions", "You set the rhythm. They enjoy the view.", "👇", "standard"),
    ("From Behind", "positions", "Classic for a reason. Deep and intense.", "🔥", "standard"),
    ("Face to Face", "positions", "Eye contact, kissing, foreheads together. Maximum connection.", "🫂", "standard"),
    ("Both at Once", "positions", "Giving and receiving at the same time. Teamwork.", "🔄", "standard"),
    ("Against the Wall", "positions", "Standing, urgent, can't-wait energy.", "🧱", "standard"),
    ("Sitting / Lap", "positions", "Wrap around each other. Deep and close.", "💺", "standard"),
    ("Edge of the Bed", "positions", "One standing, one lying back. Great angle for both.", "🛏️", "standard"),
    ("Legs Up", "positions", "Deep, intense, good stretch. Eye contact optional.", "🦵", "standard"),
    ("Facing Away", "positions", "Different angle, different sensation entirely.", "🔀", "standard"),
    ("Lying Flat", "positions", "Face down. Full body pressure and closeness.", "⬇️", "standard"),
    ("Side by Side", "positions", "Facing each other on your sides. Slow and intimate.", "✂️", "standard"),
    ("Seated on Chair", "positions", "One sits, the other straddles. Great eye contact.", "🪑", "standard"),
    ("Deep Angle", "positions", "Knees drawn up. Slow is better here.", "🧎", "standard"),
    ("Standing Behind", "positions", "Both upright. Hands free to roam.", "🚶", "standard"),
    ("Full Press", "positions", "Full weight, legs held back. Intense and close.", "🔒", "standard"),
    ("Bent Over Furniture", "positions", "Table, counter, arm of the sofa. Angle is everything.", "🪑", "standard"),
    ("Lifted Up", "positions", "Strength, urgency, legs wrapped. Effort rewarded.", "🧱", "standard"),
    ("On All Fours", "positions", "Classic and primal. Let them set the pace.", "🐾", "standard"),
    ("Over the Lap", "positions", "Draped across — intimate, vulnerable, perfect for closeness.", "🛋️", "standard"),
    ("Grinding Only", "positions", "No penetration. Find the rhythm and pressure that works.", "♀️", "standard"),
    ("Between the Thighs", "positions", "Pressed tight. Slow glide, full-body contact.", "🦵", "quick"),
    ("Just the Tip", "positions", "Full penetration withheld. Just presence and anticipation.", "💧", "quick"),
    ("From Behind with Hair Pull", "positions", "One hand gripping hair. Controlled and primal.", "🐾", "standard"),

    # ── Settings ─────────────────────────────────────────────────────────
    ("Morning Sex", "settings", "Before coffee, before plans. Just wake up and reach over.", "☀️", "quick"),
    ("In the Dark", "settings", "Pitch black. No visuals, just sound and touch.", "🌑", "quick"),
    ("Hotel Room", "settings", "Somewhere that isn't home. New bed, new energy.", "🏨", "splurge"),
    ("On the Couch", "settings", "Don't even make it to the bedroom.", "🛋️", "quick"),
    ("Bath / Hot Tub", "settings", "Warm water, skin on skin, slippery and slow.", "🛁", "standard"),
    ("Outdoors", "settings", "Balcony, tent, secluded beach. The thrill of open air.", "🌲", "splurge"),
    ("By Candlelight", "settings", "Flickering shadows, warm glow. Everything looks better.", "🕯️", "quick"),
    ("After a Date Night", "settings", "Dressed up, a little tipsy, can't keep hands off.", "🥂", "standard"),
    ("Middle of the Night", "settings", "Half asleep, reaching for each other. Dreamy and unplanned.", "🌙", "quick"),
    ("In Front of a Mirror", "settings", "Watch yourselves. See what they see.", "🪞", "standard"),
    ("Kitchen Counter", "settings", "Cooking interrupted. Dinner can wait.", "🍳", "quick"),
    ("On the Floor", "settings", "Rug, blankets, pillows. Primal and grounded.", "🔻", "quick"),
    ("Rainy Day In", "settings", "Windows fogged, nowhere to be. Let the afternoon disappear.", "🌧️", "quick"),
    ("After a Workout", "settings", "Endorphins high, bodies warm. Don't bother showering first.", "💪", "quick"),
    ("Music On", "settings", "Pick an album. Let it play start to finish.", "🎶", "quick"),
    ("In the Car", "settings", "Parked somewhere quiet. Cramped, urgent, nostalgic.", "🚗", "splurge"),
    ("Weekend Away", "settings", "New place, no routine. Reset everything.", "🧳", "splurge"),
    ("Completely Sober", "settings", "No drinks to loosen up. Just presence and choice.", "💧", "quick"),
    ("Filmed for Later", "settings", "Make a private video. Watch it together afterwards.", "📹", "standard"),
    ("Window Open", "settings", "Fresh air, a hint of risk. That's the point.", "🪟", "quick"),
    ("Fully Clothed Start", "settings", "Don't undress. Work around the fabric.", "👔", "quick"),
    ("Wake-Up Call", "settings", "Pre-agreed: wake them up however you want.", "😴", "standard"),
    ("Candlelit Scene", "settings", "Red light, soft music, everything intentional.", "🕯️", "splurge"),
    ("After a Fight", "settings", "Tension turned into something physical. Raw and real.", "🌩️", "quick"),
    ("Dress-Up Dinner", "settings", "Eat slowly, exchange looks. Then go home and drop the act.", "🍷", "splurge"),
    ("Sensory Deprivation", "settings", "Blindfold and earplugs. Only touch remains.", "🖤", "standard"),

    # ── Roleplay ─────────────────────────────────────────────────────────
    ("Strangers at a Bar", "roleplay", "Pretend you don't know each other. Flirt from scratch.", "🍸", "standard"),
    ("Power Dynamic", "roleplay", "One person is in charge. The other follows instructions.", "👑", "standard"),
    ("Massage Therapist", "roleplay", "Professional at first. Then the boundaries blur.", "💆", "standard"),
    ("Sexting First", "roleplay", "Build anticipation all day with messages. Then meet at home.", "📱", "quick"),
    ("Teacher & Student", "roleplay", "One shows, the other learns. Patient instruction.", "📖", "standard"),
    ("Dare Game", "roleplay", "Take turns daring each other. Escalate slowly.", "🎲", "standard"),
    ("Photographer", "roleplay", "One poses, the other shoots. Playful or intense.", "📸", "standard"),
    ("Wear Something New", "roleplay", "Lingerie, outfit, or costume. Surprise them with the reveal.", "🎀", "standard"),
    ("Written Instructions", "roleplay", "Leave a note with exactly what to do when they get home.", "✉️", "quick"),
    ("First Time Again", "roleplay", "Pretend it's all new. Nervous energy, asking permission.", "🦋", "standard"),
    ("Boss & Employee", "roleplay", "Classic power imbalance. One gives orders, one obeys.", "💼", "standard"),
    ("Playing Doctor", "roleplay", "Clinical tone that breaks down fast. Examination required.", "🩺", "standard"),
    ("Only Texting", "roleplay", "In the same house, only communicate by text. All night.", "💬", "quick"),
    ("Memory Replay", "roleplay", "Pick a time you both loved. Recreate it as closely as you can.", "📼", "standard"),
    ("Costume Night", "roleplay", "Full commitment — outfit, character, voice. Stay in it.", "🎭", "splurge"),
    ("Hunter & Hunted", "roleplay", "One chases, one runs — then gets caught.", "🐺", "standard"),
    ("Owned for a Night", "roleplay", "One belongs to the other. Given tasks, put on display.", "🔖", "standard"),
    ("Innocence Lost", "roleplay", "One character slowly seduced into breaking the rules.", "😇", "standard"),
    ("Obedient", "roleplay", "They don't speak unless told to. Complete compliance.", "🪆", "standard"),
    ("Confessional", "roleplay", "Tell each other the boldest thing you've thought about. In detail.", "📿", "quick"),
    ("Punishment Game", "roleplay", "They misbehave on purpose. You decide the consequence.", "📏", "standard"),
    ("Phone Line", "roleplay", "Separate rooms or separate cities. Voice only — describe everything.", "📞", "quick"),
    ("Body Platter", "roleplay", "One lies still as the surface. The other eats off their body.", "🍱", "splurge"),
    ("Pet & Owner", "roleplay", "One takes an animal role. Collar, commands, rewards.", "🐱", "standard"),
    ("Service Role", "roleplay", "In uniform (or not). Every order followed without question.", "🫧", "standard"),
    ("Interrogation", "roleplay", "One questions, one resists — until they don't. Intense.", "💡", "standard"),
    ("Wedding Night", "roleplay", "Strangers by arrangement. Nervous, curious, first-time energy.", "💍", "standard"),

    # ── Toys & Accessories ───────────────────────────────────────────────
    ("Vibrator Together", "toys-gear", "Use it on them, or let them use it while you do other things.", "〰️", "standard"),
    ("Blindfold", "toys-gear", "Take away sight. Heighten everything else.", "🖤", "quick"),
    ("Soft Restraints", "toys-gear", "Ties, scarves, or proper cuffs. Trust and surrender.", "🔗", "standard"),
    ("Massage Oil", "toys-gear", "Scented, warming, or cooling. Makes everything glide.", "🫧", "quick"),
    ("Couples Toy", "toys-gear", "Something designed for both of you to feel at the same time.", "💎", "splurge"),
    ("Lingerie", "toys-gear", "Something that makes them feel irresistible.", "🎀", "standard"),
    ("Remote Control Toy", "toys-gear", "One person holds the remote. The other holds on.", "📡", "splurge"),
    ("Feather Tickler", "toys-gear", "Light, teasing strokes across sensitive areas.", "🪶", "quick"),
    ("Warming Lubricant", "toys-gear", "Adds a slow heat that builds. Small change, big difference.", "🌡️", "quick"),
    ("Silk or Satin", "toys-gear", "Sheets, pillowcases, or a scarf. Everything feels luxurious.", "🧣", "standard"),
    ("Wand Massager", "toys-gear", "Powerful vibration. Intense and direct.", "⚡", "splurge"),
    ("Pressure Clamps", "toys-gear", "Slow build of pressure. Remove them for a new sensation.", "🔩", "standard"),
    ("Ring Toy", "toys-gear", "Sustains sensation longer. Can vibrate for both of you.", "💍", "standard"),
    ("Small Plug", "toys-gear", "Start small. The fullness adds to everything else.", "🔵", "standard"),
    ("Body-Safe Candle", "toys-gear", "Drip it slowly from height. Watch them react.", "🕯️", "standard"),
    ("Mirror Setup", "toys-gear", "Position a mirror so you can both watch.", "🪞", "quick"),
    ("Spreader Bar", "toys-gear", "Keeps things open. No hiding.", "↔️", "splurge"),
    ("Collar & Lead", "toys-gear", "Wear it, hold it. The symbolism is the point.", "🐾", "standard"),
    ("Gag", "toys-gear", "Sounds only. No words. All reaction.", "⭕", "standard"),
    ("Paddle", "toys-gear", "More impact than a hand. Leaves an impression.", "🏓", "standard"),
    ("Flogger", "toys-gear", "Multiple tails, wide impact. Warm the skin gradually.", "🎗️", "splurge"),
    ("Strap-On", "toys-gear", "Switches roles entirely. Whoever wears it leads.", "🔄", "splurge"),
    ("Body Harness", "toys-gear", "Straps across the body. Purely aesthetic power.", "🖤", "standard"),
    ("Leather Cuffs", "toys-gear", "Wrist or ankle. Padded, strong, looks the part.", "⛓️", "standard"),
    ("Bondage Tape", "toys-gear", "Sticks to itself, not skin. Wrap freely.", "🎗️", "standard"),
    ("Under-Bed Restraints", "toys-gear", "Straps under the mattress. Invisible until you need them.", "🛏️", "splurge"),
    ("Shibari Rope", "toys-gear", "Traditional Japanese bondage rope. The ritual is the point.", "🎋", "splurge"),
    ("Pinwheel", "toys-gear", "Rolled across skin. Pleasure and sharpness at the same time.", "🌀", "standard"),

    # ── Adventurous ──────────────────────────────────────────────────────
    ("Tantric / Slow", "adventurous", "No goal, no rush. Breathe together. Stay connected.", "🧘", "standard"),
    ("Light Bondage", "adventurous", "Wrists, ankles. Soft and safe. Trust is the point.", "🎗️", "standard"),
    ("Edging", "adventurous", "Get close, then stop. Repeat. The payoff is worth the wait.", "🌊", "standard"),
    ("Sensation Play", "adventurous", "Wax, ice, scratching — mix contrasts carefully.", "⚡", "standard"),
    ("Film Yourselves", "adventurous", "Make something just for you two. Delete it or keep it.", "🎥", "standard"),
    ("Read Erotica Together", "adventurous", "Pick a story. Read it aloud. See where it leads.", "📕", "quick"),
    ("Watch Together", "adventurous", "Find something you both enjoy. Use it as a warm-up.", "💻", "quick"),
    ("Quickie Challenge", "adventurous", "Set a timer. Five minutes. Make it count.", "⏱️", "quick"),
    ("New Room", "adventurous", "Somewhere in the house you haven't tried yet.", "🚪", "quick"),
    ("Marathon Session", "adventurous", "Clear the whole afternoon. No phone, no plans.", "🏔️", "splurge"),
    ("Surprise Initiation", "adventurous", "Start something when they least expect it.", "💥", "quick"),
    ("Fantasy Sharing", "adventurous", "Take turns describing a fantasy. No judgment.", "💭", "quick"),
    ("Temperature Play", "adventurous", "Ice cold one moment, body heat the next.", "🌡️", "standard"),
    ("Blindfold + Restraints", "adventurous", "Both at once. Complete surrender to touch and sound.", "🖤", "standard"),
    ("Night of Service", "adventurous", "One person's entire job is pleasing the other. Switch next time.", "🎖️", "splurge"),
    ("Discreet Teasing", "adventurous", "Remote toy, whispered words, hands under the table. Stay composed.", "😳", "standard"),
    ("Talking Challenge", "adventurous", "Whoever stops describing what they want first loses.", "🗣️", "standard"),
    ("Body Paint", "adventurous", "Skin-safe paint. Use each other as the canvas.", "🎨", "splurge"),
    ("Full Day Dynamic", "adventurous", "One leads, one follows — for a whole day. All decisions delegated.", "🎖️", "splurge"),
    ("Denial Game", "adventurous", "You decide when — and if — they get to finish.", "🌊", "standard"),
    ("Full Bondage Scene", "adventurous", "Planned, rope or restraints, full immobility. Learn safety first.", "🎗️", "splurge"),
    ("Impact Play", "adventurous", "Spanking, paddling — escalating intensity, with check-ins.", "🖐️", "standard"),
    ("Full Shibari Tie", "adventurous", "Learn and perform a complete rope tie together.", "🎋", "splurge"),
    ("Humiliation Walk", "adventurous", "Collar and lead, around the home. On display for each other.", "🐾", "standard"),
    ("Rule Night", "adventurous", "Pre-agreed rules and consequences. Enforced all evening.", "📋", "standard"),
    ("Collaring Moment", "adventurous", "Formal placement of the collar. Words, meaning, intention.", "💍", "splurge"),
    ("Contract Night", "adventurous", "Write and sign a play contract together. Limits, rules, trust.", "📜", "splurge"),
    ("Aftercare Ritual", "adventurous", "Blanket, water, holding, debriefing. The most important part.", "🫶", "quick"),
    ("Guided Relaxation", "adventurous", "Voice-guided into a deeply relaxed, suggestible state.", "🌀", "splurge"),
    ("Wax Scene", "adventurous", "Low-temp candle dripped from height. Map every reaction.", "🕯️", "standard"),
    ("Double Stimulation", "adventurous", "Toy plus partner — both at once. Go slow.", "🔵", "splurge"),
]


async def seed():
    await init_db()
    async with aiosqlite.connect(DB_PATH) as db:
        cursor = await db.execute("SELECT COUNT(*) FROM catalog_items")
        row = await cursor.fetchone()
        if row and row[0] > 0:
            print(f"Catalog already has {row[0]} items — skipping seed.")
            return

        await db.executemany(
            "INSERT INTO catalog_items (title, category, description, emoji, tier) VALUES (?,?,?,?,?)",
            CATALOG,
        )
        await db.commit()
        print(f"Seeded {len(CATALOG)} catalog items.")


if __name__ == "__main__":
    asyncio.run(seed())
